stages:
  - build
  - release
variables:
  NODE_VERSION: "22"
build:
  stage: build
  image: node:${NODE_VERSION}
  only:
    - main
    - develop
  script:
    - npm ci
    - npm run build
    - npm run zip:all
  artifacts:
    paths:
      - .output/
    expire_in: 7 days
  cache:
    paths:
      - node_modules/
release:
  stage: release
  image: node:${NODE_VERSION}
  only:
    - tags
  script:
    - npm ci
    - npm run build
    - npm run zip:all
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG"
    assets:
      links:
        - name: extension-chrome-mv3.zip
          url: https://gitlab.com/kowcio/Archivum/-/jobs/artifacts/$CI_COMMIT_TAG/raw/.output/extension-chrome-mv3.zip?job=release
        - name: extension-firefox-mv3.zip
          url: https://gitlab.com/kowcio/Archivum/-/jobs/artifacts/$CI_COMMIT_TAG/raw/.output/extension-firefox-mv3.zip?job=release
  cache:
    paths:
      - node_modules/
