import {defineConfig} from 'wxt'

// See https://wxt.dev/api/config.html
const date = `${new Date().toISOString().replace(/[-:T]/g, '').slice(0, 12)}`;

export default defineConfig({
    modules: ['@wxt-dev/module-vue', '@wxt-dev/auto-icons'],
    srcDir: 'src',
    outDir: '.output',
    publicDir: 'public',
    entrypointsDir: 'entrypoints',
    suppressWarnings: {
      firefoxDataCollection: true,
    },

    manifest: {
      name: 'Archivum - Tab Age Manager',
      description: 'Organize your browser tabs by age. Automatically group tabs into age-based groups (Week+, Month+, Quarter+, etc.) and keep your workspace organized.',
      version: '1.0.0',
      manifest_version: 3,
      permissions: ['tabs', 'activeTab', 'bookmarks', 'clipboardRead', 'storage', 'scripting', 'tabGroups', 'alarms'],
      host_permissions: ['<all_urls>'],
      // background: auto-generated by WXT from src/entrypoints/background.ts
      action: {
        default_title: 'Archivum - Tab Manager',
        default_popup: 'popup.html',
      },
      options_ui: {
        page: 'options.html',
        open_in_tab: true,
      },
      // CSP for extension pages
      content_security_policy: {
        extension_pages: "script-src 'self'; object-src 'self'",
      },
      // Firefox MV3 requires add-on ID
      browser_specific_settings: {
        gecko: {
          id: 'archivum@kowalskipiotr.pl',
          strict_min_version: '109.0',
        },
      },
      // Firefox data collection permissions (required from Nov 3, 2025)
      data_collection_permissions: {
        required: ['none'],
      },
      // Self-hosting auto-update configuration (uncomment for self-hosting)
      // update_url: 'https://yourblog.pl/extensions/archivum/update.json',
    },

    runner: {
      chromiumArgs: [
        '--window-size=1280,800',
        '--window-position=100,100',
      ],
    },

    zip: {
      // Artifact naming template with version and timestamp
      // Format: archivum-1.0.0-chrome-202607042313.zip
      artifactTemplate: `{{name}}-{{version}}-{{browser}}-${date}.zip`,
      excludeSources: [
        '**/README*',
        '**/*.md',
        '**/.github/**',
        '**/docs/**',
        '**/.copilot*',
        '**/reports/**',
        '**/test/**',
        '**/node_modules/**',
        '**/.git/**',
        '**/*.spec.ts',
        '**/playwright/**',
      ],
    },

    vite: () => ({
      define: {
        'import.meta.env.VITE_DEV_FEATURES': JSON.stringify(process.env.DEV_FEATURES || 'false'),
      },
      plugins: [
        {
          name: 'exclude-docs-from-bundle',
          generateBundle(_options: unknown, bundle: Record<string, unknown>) {
            for (const fileName of Object.keys(bundle)) {
              if (
                /README/i.test(fileName) ||
                /\.md$/i.test(fileName) ||
                /^\.github\//i.test(fileName) ||
                /^docs\//i.test(fileName)
              ) {
                delete bundle[fileName]
              }
            }
          },
        },
      ],
    }),
})
