import {defineConfig} from 'wxt'
import {readFileSync} from 'fs'
import {resolve} from 'path'

// See https://wxt.dev/api/config.html
const date = `${new Date().toISOString().replace(/[-:T]/g, '').slice(0, 12)}`;

// Generate unified version: 1.1.YYMMDDhh (Firefox-compatible: max 9 digits per number)
// Example: 1.1.26070515 = 1 . 1 . YY(26)MM(07)DD(05)HH(15)
function generateBuildVersion(): string {
  const now = new Date();

  const year = String(now.getFullYear());
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const hours = String(now.getHours()).padStart(2, '0');
  const minutes = String(now.getMinutes()).padStart(2, '0');

  return `1.${day}${month}${year}.${hours}${minutes}`;
}

const packageVersion = generateBuildVersion()

export default defineConfig({
    modules: ['@wxt-dev/module-vue', '@wxt-dev/auto-icons'],
    srcDir: 'src',
    outDir: '.output',
    publicDir: 'public',
    entrypointsDir: 'entrypoints',
    suppressWarnings: {
      // ✅ FIX #1: Suppress Firefox data collection warning
      // WXT warns about missing data_collection_permissions, but we handle it in manifest config below
      // This prevents build log spam while we explicitly set required: ['none']
      firefoxDataCollection: true,
    },

    // ✅ FIX #2: Firefox MV3 Compatibility Hook (BROWSER-SPECIFIC)
    // PROBLEM: Firefox MV3 uses scripts[], Chrome/Edge use service_worker
    // SOLUTION: Add service_worker ONLY for Chrome/Edge (not Firefox to avoid warnings)
    // WHY: Firefox ignores service_worker and uses scripts → warns about ignored property
    //      Chrome/Edge need service_worker for MV3, and ignore scripts if service_worker exists
    // Reference: https://mzl.la/firefox-mv3-migration
    hooks: {
      'build:manifestGenerated': (wxt, manifest) => {
        const isFirefox = wxt.config.browser === 'firefox';

        const bg = manifest.background as any;
        if (bg?.scripts && Array.isArray(bg.scripts)) {
          // CHROME/EDGE: Add service_worker (MV3 standard, scripts will be ignored)
          // Firefox will ignore service_worker and use scripts[] instead
          if (!isFirefox) {
            bg.service_worker = bg.scripts[0];
          }
          // FIREFOX: Keep scripts ONLY (no service_worker to avoid "BACKGROUND_SERVICE_WORKER_IGNORED" warning)
          // Firefox will use scripts[] for service worker compatibility
        }
      },
    },

    manifest: {
      name: 'Archivum - Tab manager to clear your mind',
      description: 'Organize your browser tabs by age. Automatically group tabs into age-based groups (Week+, Month+, Quarter+, etc.) and keep your workspace organized.',
      version: packageVersion,
      permissions: ['tabs', 'activeTab', 'bookmarks', 'clipboardRead', 'storage', 'scripting', 'tabGroups', 'alarms'],
      host_permissions: ['<all_urls>'],
      // background: auto-generated by WXT from src/entrypoints/background.ts
      action: {
        default_title: 'Archivum - Tab Manager',
        default_popup: 'popup.html',
      },
      options_ui: {
        page: 'options.html',
        open_in_tab: true,
      },
      // CSP for extension pages
      content_security_policy: {
        extension_pages: "script-src 'self'; object-src 'self'",
      },
      // ✅ FIX #3: Firefox MV3 Configuration
      // PROBLEM: Firefox requires add-on ID and minimum version declaration
      // SOLUTION: Use browser_specific_settings.gecko with strict_min_version
      // ✅ FIX #4: Firefox Data Collection Permissions (REQUIRED)
      // ISSUE: Mozilla requires data_collection_permissions INSIDE gecko block since Nov 3, 2025
      // IMPACT: Must be at /browser_specific_settings/gecko/data_collection_permissions
      // SOLUTION: Declare what data types your extension uses
      // OPTIONS:
      //   - required: ['none']           ← We use this (no data collection required)
      //   - required: ['personalInfo']   ← If collecting user data
      //   - optional: [...]              ← Optional data user can consent to
      browser_specific_settings: {
        gecko: {
          // Firefox add-on ID (must match what's registered on addons.mozilla.org)
          id: 'archivum@kowalskipiotr.pl',
          // UPDATED: 139.0 → 142.0
          // WHY: tabGroups requires 139+, data_collection_permissions requires 140+ (desktop) and 142+ (Android)
          // This prevents WARNING from web-ext lint about Android unsupported version
          strict_min_version: '142.0',
          // ⭐ CRITICAL: data_collection_permissions MUST be inside gecko block
          // NOT at root level! Mozilla expects it here specifically.
          // 'none' = No data collection required to use extension
          // Users won't see consent screens unless you change this
          data_collection_permissions: {
            required: ['none'],
          },
        },
      },
      // Self-hosting auto-update configuration (uncomment for self-hosting)
      // update_url: 'https://yourblog.pl/extensions/archivum/update.json',
    },

    // ✅ WEB-EXT CONFIG
    // Used by: npm run dev:firefox, npm run sign:firefox
    // Note: Updated from deprecated 'runner' to 'webExt' (WXT v0.20+ migration)
    webExt: {
      chromiumArgs: [
        '--window-size=1280,800',
        '--window-position=100,100',
      ],
    },

    // ✅ ZIP CONFIG for Publishing
    // These settings control how release packages are created
    zip: {
      // Artifact naming template with version and timestamp
      // Format: archivum-1.0.1-chrome-202607050906.zip
      // Benefits:
      //   - Version included from package.json (easy to track)
      //   - Browser included (chrome/firefox/edge)
      //   - Timestamp included (multiple builds visible)
      // Uses {{packageVersion}} to sync with package.json
      artifactTemplate: `{{name}}-{{packageVersion}}-{{browser}}-${date}.zip`,

      // ✅ IMPORTANT: Exclude sources ensures ZIPs are clean for store submission
      // web-ext lint checks these - if excluded files are present, validation may fail
      // We exclude:
      //   - Markdown docs (bloats package, not needed in production)
      //   - Source maps (debug only, increases size)
      //   - Test files (never shipped to users)
      //   - Dev config (.github, eslint, etc)
      excludeSources: [
        '**/README*',
        '**/*.md',
        '**/.github/**',
        '**/docs/**',
        '**/.copilot*',
        '**/reports/**',
        '**/test/**',
        '**/node_modules/**',
        '**/.git/**',
        '**/*.spec.ts',
        '**/playwright/**',
      ],
    },

    // ✅ VITE BUILD CONFIG
    // Customizations for production builds (npm run release, npm run build)
    vite: () => ({
      define: {
        // Feature flag for development features
        // VITE_DEV_FEATURES=true: Enables debug logging, mock data, test components
        // VITE_DEV_FEATURES=false (default): Production build, all debug hidden
        // Usage in code: if (import.meta.env.VITE_DEV_FEATURES === 'true') { ... }
        'import.meta.env.VITE_DEV_FEATURES': JSON.stringify(process.env.DEV_FEATURES || 'false'),
      },
      plugins: [
        {
          name: 'exclude-docs-from-bundle',
          // ✅ IMPORTANT: Vite plugin to remove docs from bundle
          // WHY: WXT zips source files into .output/
          // Without this, .md files and dev config bloat the package
          // web-ext lint checks for these - presence can trigger warnings
          generateBundle(_options: unknown, bundle: Record<string, unknown>) {
            for (const fileName of Object.keys(bundle)) {
              if (
                /README/i.test(fileName) ||
                /\.md$/i.test(fileName) ||
                /^\.github\//i.test(fileName) ||
                /^docs\//i.test(fileName)
              ) {
                // Remove file from final bundle
                delete bundle[fileName]
              }
            }
          },
        },
      ],
    }),
})
